// addon/src/components/Settings.tsx
import { useState, useEffect, useRef } from 'react';
import type { SecretsAPI } from '../types';
import type { Provider } from '../services/ai';

interface SettingsProps {
  secrets: SecretsAPI;
  provider: Provider;
  onProviderChange: (p: Provider) => void;
  apiKey: string;
  onApiKeyChange: (key: string) => void;
}

export function Settings({ secrets, provider, onProviderChange, apiKey, onApiKeyChange }: SettingsProps) {
  const [showKey, setShowKey] = useState(false);
  const saveTimer = useRef<ReturnType<typeof setTimeout>>(undefined);

  useEffect(() => {
    secrets.get('provider').then((p) => {
      if (p === 'openai' || p === 'anthropic') onProviderChange(p);
    }).catch(() => {});
    secrets.get('api-key').then((k) => {
      if (k) onApiKeyChange(k);
    }).catch(() => {});
  }, []);

  const handleProviderChange = (p: Provider) => {
    onProviderChange(p);
    secrets.set('provider', p).catch(() => {});
  };

  const handleKeyChange = (key: string) => {
    onApiKeyChange(key);
    // Debounce secret persistence
    clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => {
      if (key) {
        secrets.set('api-key', key).catch(() => {});
      } else {
        secrets.delete('api-key').catch(() => {});
      }
    }, 500);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
      <h3 style={{ margin: 0, fontSize: '14px', fontWeight: 600 }}>AI Provider</h3>

      <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
        <select
          value={provider}
          onChange={(e) => handleProviderChange(e.target.value as Provider)}
          style={{ padding: '6px 10px', borderRadius: '6px', border: '1px solid var(--border)', background: 'var(--background)', color: 'var(--foreground)', fontSize: '13px' }}
        >
          <option value="anthropic">Anthropic (Claude)</option>
          <option value="openai">OpenAI (GPT-5.4-mini)</option>
        </select>
      </div>

      <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
        <input
          type={showKey ? 'text' : 'password'}
          value={apiKey}
          onChange={(e) => handleKeyChange(e.target.value)}
          placeholder="Enter your API key..."
          style={{ flex: 1, padding: '6px 10px', borderRadius: '6px', border: '1px solid var(--border)', background: 'var(--background)', color: 'var(--foreground)', fontSize: '13px' }}
        />
        <button
          onClick={() => setShowKey(!showKey)}
          style={{ padding: '6px 12px', borderRadius: '6px', border: '1px solid var(--border)', background: 'transparent', color: 'var(--foreground)', cursor: 'pointer', fontSize: '13px' }}
        >
          {showKey ? 'Hide' : 'Show'}
        </button>
      </div>

      <p style={{ margin: 0, fontSize: '12px', color: 'var(--muted-foreground)' }}>
        Stored securely in Wealthfolio. Only sent to {provider === 'anthropic' ? 'Anthropic' : 'OpenAI'}.
      </p>
    </div>
  );
}

// src/lib/components/Settings.svelte
<script>
	import { app } from '$lib/stores/app.svelte.js';

	let showKey = $state(false);
</script>

<div class="card settings">
	<h2>Settings</h2>

	<div class="field">
		<label for="provider">AI Provider</label>
		<select id="provider" bind:value={app.provider}>
			<option value="anthropic">Anthropic (Claude)</option>
			<option value="openai">OpenAI (GPT-5.4-mini)</option>
		</select>
	</div>

	<div class="field">
		<label for="apiKey">API Key</label>
		<div class="key-input">
			{#if showKey}
				<input id="apiKey" type="text" bind:value={app.apiKey} placeholder="Enter your API key..." />
			{:else}
				<input id="apiKey" type="password" bind:value={app.apiKey} placeholder="Enter your API key..." />
			{/if}
			<button class="btn-secondary toggle" onclick={() => showKey = !showKey}>
				{showKey ? 'Hide' : 'Show'}
			</button>
		</div>
		<p class="muted">Your key is stored locally and only sent to {app.provider === 'anthropic' ? 'Anthropic' : 'OpenAI'}.</p>
	</div>

	{#if app.apiKey}
		<button class="btn-danger" onclick={() => app.clearSettings()}>Clear Settings</button>
	{/if}
</div>

<style>
	.settings {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.field {
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
	}

	.key-input {
		display: flex;
		gap: 0.5rem;
	}

	.key-input input {
		flex: 1;
	}

	.toggle {
		flex-shrink: 0;
		width: 4rem;
	}
</style>
