// addon/src/components/Upload.tsx
import { useState, useRef, type DragEvent, type ChangeEvent } from 'react';

const ACCEPTED = ['.pdf', '.png', '.jpg', '.jpeg'];
const MAX_SIZE_MB = 20;
const MAX_SIZE_BYTES = MAX_SIZE_MB * 1024 * 1024;

interface UploadProps {
  onFile: (file: File) => void;
  disabled?: boolean;
}

export function Upload({ onFile, disabled }: UploadProps) {
  const [dragging, setDragging] = useState(false);
  const [error, setError] = useState('');
  const inputRef = useRef<HTMLInputElement>(null);

  function validate(file: File): string | null {
    const ext = '.' + file.name.split('.').pop()?.toLowerCase();
    if (!ACCEPTED.includes(ext) && !['application/pdf', 'image/png', 'image/jpeg'].includes(file.type)) {
      return 'Unsupported file type. Please upload a PDF, PNG, or JPEG.';
    }
    if (file.size > MAX_SIZE_BYTES) {
      return `File too large (${(file.size / 1024 / 1024).toFixed(1)}MB). Max ${MAX_SIZE_MB}MB.`;
    }
    return null;
  }

  function handleFile(file: File) {
    setError('');
    const err = validate(file);
    if (err) { setError(err); return; }
    onFile(file);
  }

  function onDrop(e: DragEvent) {
    e.preventDefault();
    setDragging(false);
    const file = e.dataTransfer?.files?.[0];
    if (file) handleFile(file);
  }

  function onChange(e: ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (file) handleFile(file);
  }

  const borderColor = dragging ? 'var(--primary)' : 'var(--border)';

  return (
    <div>
      <div
        onDrop={onDrop}
        onDragOver={(e) => { e.preventDefault(); setDragging(true); }}
        onDragLeave={() => setDragging(false)}
        onClick={() => !disabled && inputRef.current?.click()}
        style={{
          border: `2px dashed ${borderColor}`,
          borderRadius: '8px',
          padding: '40px 20px',
          textAlign: 'center',
          cursor: disabled ? 'not-allowed' : 'pointer',
          opacity: disabled ? 0.5 : 1,
          transition: 'border-color 0.15s',
        }}
      >
        <p style={{ margin: 0, fontWeight: 500 }}>Drop a PDF or image here, or click to browse</p>
        <p style={{ margin: '4px 0 0', fontSize: '12px', color: 'var(--muted-foreground)' }}>
          PDF, PNG, JPEG — up to {MAX_SIZE_MB}MB
        </p>
      </div>
      <input ref={inputRef} type="file" accept={ACCEPTED.join(',')} onChange={onChange} hidden />
      {error && (
        <p style={{ marginTop: '8px', padding: '8px 12px', borderRadius: '6px', background: 'hsl(0 84% 60% / 0.1)', color: 'hsl(0 84% 60%)', fontSize: '13px' }}>
          {error}
        </p>
      )}
    </div>
  );
}

// src/lib/components/Upload.svelte
<script>
	const ACCEPTED_TYPES = ['application/pdf', 'image/png', 'image/jpeg'];
	const ACCEPTED_EXTENSIONS = ['.pdf', '.png', '.jpg', '.jpeg'];
	const MAX_SIZE_MB = 20;
	const MAX_SIZE_BYTES = MAX_SIZE_MB * 1024 * 1024;

	let { onfile } = $props();
	let dragging = $state(false);
	let error = $state('');

	function validate(file) {
		if (!file) return 'No file selected.';
		const ext = '.' + file.name.split('.').pop().toLowerCase();
		if (!ACCEPTED_TYPES.includes(file.type) && !ACCEPTED_EXTENSIONS.includes(ext)) {
			return `Unsupported file type. Please upload a PDF, PNG, or JPEG file.`;
		}
		if (file.size > MAX_SIZE_BYTES) {
			return `File is too large (${(file.size / 1024 / 1024).toFixed(1)}MB). Maximum is ${MAX_SIZE_MB}MB.`;
		}
		return null;
	}

	function handleFile(file) {
		error = '';
		const err = validate(file);
		if (err) {
			error = err;
			return;
		}
		onfile(file);
	}

	function ondrop(e) {
		e.preventDefault();
		dragging = false;
		const file = e.dataTransfer?.files?.[0];
		if (file) handleFile(file);
	}

	function ondragover(e) {
		e.preventDefault();
		dragging = true;
	}

	function ondragleave() {
		dragging = false;
	}

	function onchange(e) {
		const file = e.target.files?.[0];
		if (file) handleFile(file);
	}
</script>

<div class="card">
	<h2>Upload Document</h2>

	<!-- svelte-ignore a11y_no_static_element_interactions -->
	<div
		class="dropzone"
		class:dragging
		{ondrop}
		{ondragover}
		{ondragleave}
		onclick={() => document.getElementById('file-input').click()}
		onkeydown={(e) => { if (e.key === 'Enter' || e.key === ' ') document.getElementById('file-input').click(); }}
		role="button"
		tabindex="0"
	>
		<p class="dropzone-text">Drop a PDF or image here, or click to browse</p>
		<p class="muted">Supports PDF, PNG, JPEG — up to {MAX_SIZE_MB}MB</p>
	</div>

	<input
		id="file-input"
		type="file"
		accept={ACCEPTED_EXTENSIONS.join(',')}
		{onchange}
		hidden
	/>

	{#if error}
		<p class="error">{error}</p>
	{/if}
</div>

<style>
	.dropzone {
		border: 2px dashed var(--color-border);
		border-radius: var(--radius);
		padding: 3rem 1.5rem;
		text-align: center;
		cursor: pointer;
		transition: border-color 0.15s, background 0.15s;
	}

	.dropzone:hover, .dragging {
		border-color: var(--color-primary);
		background: color-mix(in srgb, var(--color-primary) 5%, transparent);
	}

	.dropzone-text {
		font-weight: 500;
		margin-bottom: 0.25rem;
	}

	.error {
		margin-top: 0.75rem;
	}
</style>
