// src/lib/components/ReviewTable.svelte
<script>
	import { ACTIVITY_TYPES } from '$lib/prompt.js';
	import { generateCSV, downloadCSV } from '$lib/services/csv.js';

	let { transactions = $bindable(), onstartover } = $props();

	function addRow() {
		transactions = [...transactions, {
			date: new Date().toISOString(),
			symbol: '',
			quantity: 0,
			activityType: 'BUY',
			unitPrice: 0,
			currency: 'USD',
			fee: 0,
			amount: 0
		}];
	}

	function deleteRow(index) {
		transactions = transactions.filter((_, i) => i !== index);
	}

	function handleDownload() {
		const csv = generateCSV(transactions);
		downloadCSV(csv);
	}
</script>

<div class="card review">
	<div class="review-header">
		<h2>Review Transactions ({transactions.length})</h2>
		<div class="review-actions">
			<button class="btn-secondary" onclick={addRow}>+ Add Row</button>
			<button class="btn-primary" onclick={handleDownload} disabled={transactions.length === 0}>
				Download CSV
			</button>
		</div>
	</div>

	{#if transactions.length === 0}
		<p class="muted">No transactions extracted. You can add rows manually or try a different document.</p>
	{:else}
		<div class="table-wrapper">
			<table>
				<thead>
					<tr>
						<th>Date</th>
						<th>Symbol</th>
						<th>Qty</th>
						<th>Type</th>
						<th>Unit Price</th>
						<th>Currency</th>
						<th>Fee</th>
						<th>Amount</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					{#each transactions as row, i}
						<tr>
							<td><input type="text" bind:value={row.date} class="col-date" /></td>
							<td><input type="text" bind:value={row.symbol} class="col-symbol" /></td>
							<td><input type="number" bind:value={row.quantity} step="any" class="col-num" /></td>
							<td>
								<select bind:value={row.activityType}>
									{#each ACTIVITY_TYPES as t}
										<option value={t}>{t}</option>
									{/each}
								</select>
							</td>
							<td><input type="number" bind:value={row.unitPrice} step="any" class="col-num" /></td>
							<td><input type="text" bind:value={row.currency} class="col-currency" /></td>
							<td><input type="number" bind:value={row.fee} step="any" class="col-num" /></td>
							<td><input type="number" bind:value={row.amount} step="any" class="col-num" /></td>
							<td>
								<button class="btn-delete" onclick={() => deleteRow(i)} title="Delete row">&times;</button>
							</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	{/if}

	<div class="bottom-actions">
		<button class="btn-secondary" onclick={onstartover}>Start Over</button>
	</div>
</div>

<style>
	.review {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.review-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		flex-wrap: wrap;
		gap: 0.5rem;
	}

	.review-actions {
		display: flex;
		gap: 0.5rem;
	}

	.table-wrapper {
		overflow-x: auto;
		-webkit-overflow-scrolling: touch;
	}

	table {
		width: 100%;
		border-collapse: collapse;
		font-size: 0.8125rem;
	}

	th {
		text-align: left;
		padding: 0.5rem 0.25rem;
		border-bottom: 2px solid var(--color-border);
		font-weight: 600;
		white-space: nowrap;
	}

	td {
		padding: 0.25rem;
		border-bottom: 1px solid var(--color-border);
	}

	td input, td select {
		font-size: 0.8125rem;
		padding: 0.25rem 0.5rem;
		border-radius: 4px;
	}

	.col-date { width: 11rem; min-width: 11rem; }
	.col-symbol { width: 6rem; min-width: 5rem; }
	.col-num { width: 6rem; min-width: 5rem; }
	.col-currency { width: 4rem; min-width: 3.5rem; }

	td select {
		width: 8rem;
		min-width: 7rem;
	}

	.btn-delete {
		background: none;
		color: var(--color-error);
		font-size: 1.25rem;
		line-height: 1;
		padding: 0.125rem 0.5rem;
	}

	.btn-delete:hover {
		background: var(--color-error);
		color: white;
		border-radius: 4px;
	}

	.bottom-actions {
		display: flex;
		justify-content: flex-start;
	}
</style>

// addon/src/components/ReviewTable.tsx
import React from 'react';
import { ACTIVITY_TYPES, type ExtractedTransaction } from '../services/prompt';

interface ReviewTableProps {
  transactions: ExtractedTransaction[];
  onChange: (transactions: ExtractedTransaction[]) => void;
}

export function ReviewTable({ transactions, onChange }: ReviewTableProps) {
  function updateRow(index: number, field: keyof ExtractedTransaction, value: string | number) {
    const updated = [...transactions];
    updated[index] = { ...updated[index], [field]: value };
    onChange(updated);
  }

  function deleteRow(index: number) {
    onChange(transactions.filter((_, i) => i !== index));
  }

  function addRow() {
    onChange([
      ...transactions,
      {
        date: new Date().toISOString(),
        symbol: '',
        quantity: 0,
        activityType: 'BUY',
        unitPrice: 0,
        currency: 'USD',
        fee: 0,
        amount: 0,
      },
    ]);
  }

  const cellStyle: React.CSSProperties = {
    padding: '4px',
    borderBottom: '1px solid var(--border)',
  };

  const inputStyle: React.CSSProperties = {
    width: '100%',
    padding: '4px 8px',
    borderRadius: '4px',
    border: '1px solid var(--border)',
    background: 'var(--background)',
    color: 'var(--foreground)',
    fontSize: '12px',
    boxSizing: 'border-box',
  };

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
        <span style={{ fontSize: '13px', color: 'var(--muted-foreground)' }}>
          {transactions.length} transaction{transactions.length !== 1 ? 's' : ''}
        </span>
        <button
          onClick={addRow}
          style={{ padding: '4px 12px', borderRadius: '6px', border: '1px solid var(--border)', background: 'transparent', color: 'var(--foreground)', cursor: 'pointer', fontSize: '12px' }}
        >
          + Add Row
        </button>
      </div>

      {transactions.length === 0 ? (
        <p style={{ textAlign: 'center', padding: '20px', color: 'var(--muted-foreground)', fontSize: '13px' }}>
          No transactions extracted. Try a different document or add rows manually.
        </p>
      ) : (
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '12px' }}>
            <thead>
              <tr>
                {['Date', 'Symbol', 'Qty', 'Type', 'Price', 'CCY', 'Fee', 'Amount', ''].map((h) => (
                  <th key={h} style={{ ...cellStyle, textAlign: 'left', fontWeight: 600, borderBottom: '2px solid var(--border)', whiteSpace: 'nowrap' }}>
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {transactions.map((row, i) => (
                <tr key={i}>
                  <td style={cellStyle}>
                    <input style={{ ...inputStyle, minWidth: '160px' }} value={row.date} onChange={(e) => updateRow(i, 'date', e.target.value)} />
                  </td>
                  <td style={cellStyle}>
                    <input style={{ ...inputStyle, minWidth: '80px' }} value={row.symbol} onChange={(e) => updateRow(i, 'symbol', e.target.value)} />
                  </td>
                  <td style={cellStyle}>
                    <input style={{ ...inputStyle, minWidth: '70px' }} type="number" step="any" value={row.quantity} onChange={(e) => updateRow(i, 'quantity', +e.target.value)} />
                  </td>
                  <td style={cellStyle}>
                    <select
                      style={{ ...inputStyle, minWidth: '100px' }}
                      value={row.activityType}
                      onChange={(e) => updateRow(i, 'activityType', e.target.value)}
                    >
                      {ACTIVITY_TYPES.map((t) => (
                        <option key={t} value={t}>{t}</option>
                      ))}
                    </select>
                  </td>
                  <td style={cellStyle}>
                    <input style={{ ...inputStyle, minWidth: '80px' }} type="number" step="any" value={row.unitPrice} onChange={(e) => updateRow(i, 'unitPrice', +e.target.value)} />
                  </td>
                  <td style={cellStyle}>
                    <input style={{ ...inputStyle, minWidth: '50px' }} value={row.currency} onChange={(e) => updateRow(i, 'currency', e.target.value)} />
                  </td>
                  <td style={cellStyle}>
                    <input style={{ ...inputStyle, minWidth: '60px' }} type="number" step="any" value={row.fee} onChange={(e) => updateRow(i, 'fee', +e.target.value)} />
                  </td>
                  <td style={cellStyle}>
                    <input style={{ ...inputStyle, minWidth: '80px' }} type="number" step="any" value={row.amount} onChange={(e) => updateRow(i, 'amount', +e.target.value)} />
                  </td>
                  <td style={cellStyle}>
                    <button
                      onClick={() => deleteRow(i)}
                      title="Delete row"
                      style={{ background: 'none', border: 'none', color: 'hsl(0 84% 60%)', cursor: 'pointer', fontSize: '16px', padding: '2px 6px' }}
                    >
                      ×
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
